### ISSUE TITLE
 tag disqus on line 20 in /_layouts/post.html is not a recognized Liquid tag

### ISSUE THREAD

**Issue by truesnow** [ronv/colorie#2]
Hi, ronv,
  I fork your repo, and the GitHub Pages occur an error said:

```
Your site is having problems building: The tag disqus on line 20 in /_layouts/post.html is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.
```

![image](https://user-images.githubusercontent.com/37447603/89118110-b9e2ea00-d4d5-11ea-8b18-c6cfd11bebc1.png)

**Comment by p3r7** [comment]
Github pages only allows a very limited set of jekyll plugins: https://pages.github.com/versions/

This Jekyll "template" uses some plugins that are not supported.

There are some tricks to circumvent this (copying the source of a plugin directly in the source of your files) but they are hackish.

An alternative is to host on a provider which is less limiting, such as https://app.netlify.com/ (also free).

Source: I built [my blog](https://www.eigenbahn.com/) from this template with minimum modifications.

**Comment by truesnow** [comment]
@p3r7 Many thanks to your reply. I'm newly use of Jekyll, your reply let me learned a lot. I removed disqus in my project finally.

**Comment by ronv** [comment]
thanks @p3r7 for help! yes it uses costume plugin. have checked options to host it on netlify @truesnow ?

**Comment by truesnow** [comment]
@ronv After remove disqus, I can use GitHub Pages for now, maybe I'll try netlify next time. BTW, thanks for your theme, I like it.
